num_2_item_dict: {"1": "champion_copper_plus_spark_plug",
            "2": "cheezit_big_original",
            "3": "crayola_64_ct",
            "4": "elmers_washable_no_run_school_glue",
            "5": "expo_dry_erase_board_eraser",
            "6": "feline_greenies_dental_treats",
            "7": "genuine_joe_plastic_stir_sticks",
            "8": "highland_6539_self_stick_notes",
            "9": "kong_air_dog_squeakair_tennis_ball",
            "10": "kong_duck_dog_toy",
            "11": "kyjen_squeakin_eggs_plush_puppies",
            "12": "mead_index_cards",
            "13": "mommys_helper_outlet_plugs",
            "14": "oreo_mega_stuf",
            "15": "safety_works_safety_glasses",
            "16": "sharpie_accent_tank_style_highlighters",
            "17": "stanley_66_052",
            "18": "first_years_take_and_toss_straw_cup"}